### ISSUE TITLE
cr flag causes error on tundra network

### ISSUE THREAD

**Issue by hallucigenia-sparsa** [ramellose/manta#1]
Tundra network, call: manta -i tundra_network.cyjs -o tundra_network_clustered.cyjs --layout -cr

[tundra_network.cyjs.zip](https://github.com/ramellose/manta/files/3907320/tundra_network.cyjs.zip)

works fine without cr flag

Traceback (most recent call last):
  File "/anaconda3/bin/manta", line 10, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.7/site-packages/manta/main.py", line 272, in main
    error=args['error'], verbose=args['verbose'])
  File "/anaconda3/lib/python3.7/site-packages/manta/reliability.py", line 356, in perm_clusters
    for i in range(relperms):
TypeError: 'float' object cannot be interpreted as an integer

**Comment by ramellose** [comment]
The relperms internal parameter is calculated as the fraction of possible edge swaps divided by the total number of swaps. This can be a float - current fix converts to int.
