### ISSUE TITLE
Error during partial diffusion

### ISSUE THREAD

**Issue by nguyenlienviet** [ramellose/manta#6]
First of all, thanks for providing this tool! It is just what I need for my Master's thesis. The tool worked fine on some datasets, but for others it's throwing the error below. Have you encountered this?

```
2021-05-25 11:40:42,306 - manta.cluster - INFO - This is a balanced network, so you may be able to get good results with the Kernighan-Lin algorithm.
2021-05-25 11:40:42,609 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2021-05-25 11:40:42,610 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2021-05-25 11:40:42,610 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2021-05-25 11:40:42,610 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2021-05-25 11:40:42,610 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2021-05-25 11:40:42,610 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2021-05-25 11:40:42,610 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2021-05-25 11:40:42,610 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2021-05-25 11:40:42,610 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2021-05-25 11:40:42,610 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2021-05-25 11:40:42,610 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2021-05-25 11:40:42,610 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2021-05-25 11:40:42,610 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2021-05-25 11:40:42,611 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2021-05-25 11:40:42,611 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
2021-05-25 11:40:42,611 - manta.flow - ERROR - Unable to run partial diffusion. Try increasing the number of iterations.
Traceback (most recent call last):
  File "/home/nguyenlienviet/.local/bin/manta", line 8, in <module>
    sys.exit(main())
  File "/home/nguyenlienviet/.local/lib/python3.6/site-packages/manta/main.py", line 281, in main
    permutations=args['perm'], verbose=args['verbose'])
  File "/home/nguyenlienviet/.local/lib/python3.6/site-packages/manta/cluster.py", line 104, in cluster_graph
    ratio=ratio, permutations=permutations, verbose=verbose)
  File "/home/nguyenlienviet/.local/lib/python3.6/site-packages/manta/flow.py", line 309, in partial_diffusion
    pos_sums = result[b][pos_results]
IndexError: list index out of range
```

[Here](https://drive.google.com/file/d/1fgrokfwF_zAW1U7hzYWnUw1NiwkevgWL/view?usp=sharing) is the network that's causing this problem. The edges are calculated using [SparCC](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1002687)

**Comment by ramellose** [comment]
Hi, thanks for your interest in manta! These issues can happen when networks are too small; in that case, the partial_diffusion function only returns matrices containing zeroes which cannot be used to cluster the network. As suggested by the error, you can try increasing the number of iterations, or you can increase the fraction of the network used for partial_diffusion by changing the -subset parameter.

**Comment by ane1233** [comment]
Hi, I am running into the same issue as the user above. I tried increasing the number of iterations and changing the subset parameter. Is there another option? 

I have about 300 samples in my dataset.
